version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^/approve
      enabled: true
      reject_regex: ^/reject
    required: 1
    reset_on_push:
      enabled: true
    users:
    - iBug
    - taoky
