version: 2
groups:
  code-admins:
    approve_by_comment:
      approve_regex: ^\/approve
      enabled: true
      reject_regex: ^\/reject
    required: 1
    reset_on_push:
      enabled: true
    author_approval:
      ignored: true
    users:
    - iBug
    - taoky
